{% set name = "huggingface_hub" %}

package:
  name: "{{ name|lower }}"
  version: "{{ HUB_VERSION }}"

source:
  path: ../../

build:
  noarch: python

requirements:
  host:
    - python
    - pip
    - fsspec
    - filelock
    - httpx
    - tqdm
    - typing-extensions
    - packaging
    - pyyaml
    - hf-xet
  run:
    - python
    - pip
    - filelock
    - httpx
    - tqdm
    - typing-extensions
    - packaging
    - pyyaml
    - hf-xet
test:
  imports:
    - huggingface_hub

about:
  home: https://huggingface.co
  license: Apache License 2.0
  license_file: LICENSE
  summary: "Client library to download and publish models and other files on the huggingface.co hub"
