# Code generated by jtd-codegen for Python v0.3.1

from dataclasses import dataclass, field
from typing import Any, List, Optional

from typing_extensions import TypeAlias


ModelIndexSet: TypeAlias = "List[ModelIndex]"


@dataclass
class ModelIndex:
    name: str
    results: "List[SingleResult]"


@dataclass
class SingleMetric:
    type: str
    """
    Example: wer
    """

    value: Any
    """
    Example: 20.0 or "20.0 ± 1.2"
    """

    args: Any = field(default=None)
    name: Optional[str] = field(default=None)


@dataclass
class SingleResultTask:
    type: str
    """
    Example: automatic-speech-recognition Use task id from
    https://github.com/huggingface/huggingface_hub/blob/main/js/src/lib/int
    erfaces/Types.ts
    """

    name: Optional[str] = None
    """
    Example: Speech Recognition
    """


@dataclass
class SingleResultDataset:
    """
    This will switch to required at some point. in any case, we need them to
    link to PWC
    """

    name: str
    """
    Example: Common Voice (French). A pretty name for the dataset.
    """

    type: str
    """
    Example: common_voice. Use dataset id from https://hf.co/datasets
    """

    config: Optional[str] = None
    """
    Example: fr. The name of the dataset configuration used in `load_dataset()`
    """

    split: Optional[str] = None
    """
    Example: test.
    """

    revision: Optional[str] = None
    """
    Example: 5503434ddd753f426f4b38109466949a1217c2bb.
    """

    args: Any = None
    """
    Example: zh-CN
    """


@dataclass
class SingleResult:
    task: "SingleResultTask"
    dataset: "Optional[SingleResultDataset]"
    metrics: "List[SingleMetric]"
    """
    This will switch to required at some point. in any case, we need them to
    link to PWC
    """
