name: "\U0001F41B Bug Report"
description: Report a bug on huggingface_hub
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a pull request for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a minimal reproducible code which we can copy/paste and reproduce the issue.
      placeholder: Reproduction
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please include the Python logs if you can. If possible, run the code with `HF_DEBUG=1` as environment variable."
      render: shell
  - type: textarea
    id: system-info
    attributes:
      label: System info
      description: |
        Please dump your environment info by running the following command and copy-paste the result here:
        ```txt
        huggingface-cli env
        ```

        If you are working in a notebook, please run it in a code cell:
        ```py
        from huggingface_hub import dump_environment_info

        dump_environment_info()
        ```
      render: shell
      placeholder: |
        - huggingface_hub version: 0.11.0.dev0
        - Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
        - Python version: 3.10.6
        ...
    validations:
      required: true
