# ruff: noqa: F401
# Import modules individually to avoid circular dependencies
from . import (
    _common,
    audio_classification,
    audio_to_audio,
    automatic_speech_recognition,
    conversational,
    document_question_answering,
    feature_extraction,
    fill_mask,
    image_classification,
    image_segmentation,
    image_to_image,
    image_to_text,
    object_detection,
    question_answering,
    sentence_similarity,
    table_question_answering,
    tabular_classification,
    text_classification,
    text_to_image,
    text_to_speech,
    token_classification,
    translation,
    zero_shot_classification,
    zero_shot_image_classification,
)
