name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@0ab9ea03baf111ed8dd83e88233430b663127368  # main
    with:
      commit_sha: ${{ github.sha }}
      package: huggingface_hub
      languages: cn de fr en hi ko or ta
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
