name: Build and push Model Card and Dataset Card examples

on:
  push:
    branches:
      - main

env:
  HF_TOKEN: ${{ secrets.HUGGINGFACE_PRODUCTION_USER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: 3.13

      # Install dependencies
      - name: Configure and install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install Jinja2

      # Push cards
      - name: Push cards
        run: python utils/push_repocard_examples.py
