name: Build and push Model Card and Dataset Card examples

on:
  push:
    branches:
      - main

env:
  HF_TOKEN: ${{ secrets.HUGGINGFACE_PRODUCTION_USER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: 3.13

      # Install dependencies
      - name: Configure and install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install Jinja2

      # Push cards
      - name: Push cards
        run: python utils/push_repocard_examples.py
