name: Python release

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g., v0.30.0)"
        required: true

env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_DIST_HF }}

jobs:
  python_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel

      - run: cd utils/hf && python setup.py sdist bdist_wheel

      - run: |
          pip install twine

      - name: Upload to PyPI
        run: |
          cd utils/hf && twine upload dist/* -u __token__ -p "$PYPI_TOKEN"
