name: Style Bot

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to run style checks on'
        required: false
        type: number
        default: 0

permissions:
  contents: write
  pull-requests: write

jobs:
  style:
    uses: ./.github/workflows/style-bot-action.yml
    with:
      python_quality_dependencies: "[quality]"
      style_command_type: "style_only"
      pr_number: ${{ fromJSON(inputs.pr_number) }}
    secrets:
      bot_token: ${{ secrets.GITHUB_TOKEN }}